config/routes.rb
Rails.application.routes.draw do
  resources :leasons
  resources :users

   root 'users#index'

end

app/models/leason.rb
class Leason < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/leasons_controller.rb
class LeasonsController < ApplicationController
  before_action :set_leason, only: [:show, :edit, :update, :destroy]

  # GET /leasons
  # GET /leasons.json
  def index
    @leasons = Leason.all
  end

  # GET /leasons/1
  # GET /leasons/1.json
  def show
  end

  # GET /leasons/new
  def new
    @leason = Leason.new
  end

  # GET /leasons/1/edit
  def edit
  end

  # POST /leasons
  # POST /leasons.json
  def create
    @leason = Leason.new(leason_params)

    respond_to do |format|
      if @leason.save
        format.html { redirect_to @leason, notice: 'Leason was successfully created.' }
        format.json { render :show, status: :created, location: @leason }
      else
        format.html { render :new }
        format.json { render json: @leason.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /leasons/1
  # PATCH/PUT /leasons/1.json
  def update
    respond_to do |format|
      if @leason.update(leason_params)
        format.html { redirect_to @leason, notice: 'Leason was successfully updated.' }
        format.json { render :show, status: :ok, location: @leason }
      else
        format.html { render :edit }
        format.json { render json: @leason.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leasons/1
  # DELETE /leasons/1.json
  def destroy
    @leason.destroy
    respond_to do |format|
      format.html { redirect_to leasons_url, notice: 'Leason was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_leason
      @leason = Leason.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def leason_params
      params.require(:leason).permit(:class_name, :start, :end)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:user_name, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/leasons_helper.rb
module LeasonsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AppSql</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/leasons/_form.html.erb
<%= form_for(@leason) do |f| %>
  <% if @leason.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@leason.errors.count, "error") %> prohibited this leason from being saved:</h2>

      <ul>
      <% @leason.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :class_name %><br>
    <%= f.text_field :class_name %>
  </div>
  <div class="field">
    <%= f.label :start %><br>
    <%= f.text_field :start %>
  </div>
  <div class="field">
    <%= f.label :end %><br>
    <%= f.text_field :end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/leasons/edit.html.erb
<h1>Editing Leason</h1>

<%= render 'form' %>

<%= link_to 'Show', @leason %> |
<%= link_to 'Back', leasons_path %>

app/views/leasons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Leasons</h1>

<table>
  <thead>
    <tr>
      <th>Class name</th>
      <th>Start</th>
      <th>End</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @leasons.each do |leason| %>
      <tr>
        <td><%= leason.class_name %></td>
        <td><%= leason.start %></td>
        <td><%= leason.end %></td>
        <td><%= link_to 'Show', leason %></td>
        <td><%= link_to 'Edit', edit_leason_path(leason) %></td>
        <td><%= link_to 'Destroy', leason, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Leason', new_leason_path %>

app/views/leasons/new.html.erb
<h1>New Leason</h1>

<%= render 'form' %>

<%= link_to 'Back', leasons_path %>

app/views/leasons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Class name:</strong>
  <%= @leason.class_name %>
</p>

<p>
  <strong>Start:</strong>
  <%= @leason.start %>
</p>

<p>
  <strong>End:</strong>
  <%= @leason.end %>
</p>

<%= link_to 'Edit', edit_leason_path(@leason) %> |
<%= link_to 'Back', leasons_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_name %><br>
    <%= f.text_field :user_name %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>User name</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.user_name %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User name:</strong>
  <%= @user.user_name %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>